orbs:
  docker: circleci/docker@1.7.0
version: 2.1

workflows:
    example-workflow:
      jobs:
        - docker/publish:
            deploy: true 
            image: curedao/php-8.1-apache-buster-xdebug-opcache-composer-pgsql 
