name: ci

runs-on: [self-hosted]

on:
  push:
    branches:
      - "master"
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

steps:
  - uses: actions/checkout@v1.0
    name: Check out code

  - uses: mr-smithers-excellent/docker-build-push@v3
    name: Build & push Docker image
    with:
      image: curedao/php-8.1-apache-buster-xdebug-opcache-composer-pgsql
      registry: docker.io
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
